#! CUSTOM USER VARIABLES
VSPHERE_WORKER_NUM_CPUS_1: 2
VSPHERE_WORKER_NUM_CPUS_2: 2
VSPHERE_WORKER_DISK_GIB_1: 40
VSPHERE_WORKER_DISK_GIB_2: 50
VSPHERE_WORKER_MEM_MIB_1: 4096
VSPHERE_WORKER_MEM_MIB_2: 4096
ENABLE_METRICS_SERVER: false
INSTALL_KYVERNO: false
KYVERNO_ENFORCE_BASELINE: false
KYVERNO_AUDIT_BASELINE: false
ENABLE_SVC_LB_KUBEVIP: false
KUBEVIP_GLOBAL_VIP_CIDR:
ENABLE_SVC_LB_METALLB: false
METALLB_VIP_RANGE: 
ENABLE_OSS_CONTOUR: false
ENABLE_OSS_MONITORING_STACK: false
