#! CUSTOM USER VARIABLES
VSPHERE_WORKER_NUM_CPUS_1: 2
VSPHERE_WORKER_NUM_CPUS_2: 2
VSPHERE_WORKER_DISK_GIB_1: 25
VSPHERE_WORKER_DISK_GIB_2: 25
VSPHERE_WORKER_MEM_MIB_1: 4096
VSPHERE_WORKER_MEM_MIB_2: 4096
ENABLE_METRICS_SERVER: false
INSTALL_KYVERNO: false
KYVERNO_ENFORCE_BASELINE: false
KYVERNO_AUDIT_BASELINE: false
ENABLE_SVC_LB_KUBEVIP: false
KUBEVIP_GLOBAL_VIP_CIDR:
ENABLE_SVC_LB_METALLB: false
METALLB_VIP_RANGE:
ENABLE_OSS_CONTOUR: false
ENABLE_OSS_HARBOR: false
HARBOR_OSS_FQDN:
HARBOR_OSS_PASSWORD:
ENABLE_OSS_MONITORING_STACK: false
ENABLE_KUBEAPPS: false
KUBEAPPS_HOSTNAME:
ENABLE_TKG_MONITORING_STACK: false
PROMETHEUS_FQDN:
GRAFANA_PASSWORD:
GRAFANA_FQDN:
ATTACH_TO_TMC: false
TMC_API_TOKEN:
TMC_CLUSTER_GROUP_NAME: "tkg-clusters"
TMC_ENABLE_DATA_PROTECTION: "false"
TMC_DATA_PROTECTION_ACCOUNT_NAME: ""
INSTALL_RANCHER: false
RANCHER_FQDN:
ENABLE_OSS_CERT_MANAGER: false
HARBOR_OSS_NOTARY_FQDN:
